#!/usr/bin/env bash
# Script that configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
